# Load this file from your Apache httpd.conf:
# Include "F:/sam/apache/httpd-sam-include.conf"

Listen 127.0.0.1:8088

LoadModule rewrite_module modules/mod_rewrite.so

Include "F:/sam/apache/sam-vhost.conf"
